import pygame
pygame.init()

#window
SCREEN_WIDTH, SCREEN_HEIGHT = 1920, 1080
FRAMERATE = 60
GAME_ICON = 'Greasy Kingx/GameIcon.PNG'

#entities
ENTITY_SIZE = (max(0.052 * SCREEN_WIDTH, 0.092 * SCREEN_HEIGHT), max(0.052 * SCREEN_WIDTH, 0.092 * SCREEN_HEIGHT))

GREASY_KILLER_ICON = 'Greasy Kingx/GreasyKiller.PNG'
GREASY_KILLER_MOVEMENT_SPEED = 0.005 * SCREEN_WIDTH
GREASY_KILLER_HEALTH = 100

SLICKBACK_SCOUNDREL_ICON = 'Greasy Kingx/SlickBackScoundrel.PNG'
SLICKBACK_SCOUNDREL_MOVEMENT_SPEED = 0.003 * SCREEN_WIDTH
SLICKBACK_SCOUNDREL_BODY_DAMAGE = 30
SLICKBACK_SCOUNDREL_HEALTH = 50

#weapons

#dagger
DAGGER_ICON = 'Greasy Kingx/Dagger.PNG'
DAGGER_SIZE = (0.104 * SCREEN_WIDTH, 0.018 * SCREEN_HEIGHT)
DAGGER_SPAN = 90
DAGGER_SPEED = 1
DAGGER_DAMAGE = 25

#bow
BOW_ICON = 'Greasy Kingx/Bow.PNG'
BOW_SIZE = (0.028 * SCREEN_WIDTH, 0.092 * SCREEN_HEIGHT)
BOW_PROJECTILE_SPEED = 1
BOW_PROJECTILE_SIZE = (0.016 * SCREEN_WIDTH, 0.009 * SCREEN_HEIGHT)
BOW_PROJECTILE_DAMAGE = 20
BOW_PROJECTILE_ICON = 'Greasy Kingx/BowProjectile.PNG'

#text
FONT_SIZE = SCREEN_WIDTH // 40
TEXT_FONT = pygame.font.Font(None, FONT_SIZE)
GAME_TUTORIAL = 'How to play:\n\nW,A,S,D - Movement\n\nMouse Click\Spacebar - Shoot\Slash at\ncursor direction\n\nP - Pause\n\n0,...,9 - Select Item\n\n'

#score
SCORE_COLOR = (255, 148, 160)

#quick item list
QUICK_ITEMS_WIDTH = 0.532 * SCREEN_WIDTH
QUICK_ITEMS_HEIGHT = 100
QUICK_ITEMS_COLOR = (187, 220, 240)
QUICK_ITEMS_BORDER_RADIUS = 15

#health bar
HEALTHBAR_WIDTH = 0.234 * SCREEN_WIDTH
HEALTHBAR_HEIGHT = 0.037 * SCREEN_HEIGHT
HEALTHBAR_BG_COLOR = (255, 122, 122)
HEALTHBAR_COLOR = (255, 0, 0)
HEALTHBAR_BORDER_RADIUS = 40

#main menu
MAIN_MENU_COLOR = (97, 102, 201)
MAIN_MENU_BORDER_RADIUS = 40

MAIN_MENU_BUTTON_COLOR = (30, 34, 115)
MAIN_MENU_BUTTON_BORDER_RADIUS = 10

MAIN_MENU_TEXT_COLOR = (255, 255, 255)

#resume screen
RESUME_BACKGROUND_COLOR = (156, 40, 201)
RESUME_FONT = pygame.font.Font(None, FONT_SIZE)
RESUME_TEXT_COLOR = (255, 255, 255)
RESUME_DURATION = 3

#shop screen
SHOP_COLOR = (97, 102, 201)
SHOP_BORDER_RADIUS = 40
SHOP_BUTTON_COLOR = (30, 34, 115)
SHOP_BUTTON_BORDER_RADIUS = 10
SHOP_TEXT_COLOR = (255, 255, 255)

#death screen
DEATH_SCREEN_WIDTH = 0.5 * SCREEN_WIDTH
DEATH_SCREEN_HEIGHT = 0.33 * SCREEN_HEIGHT
DEATH_SCREEN_COLOR = (255, 0, 0)
DEATH_SCREEN_BORDER_RADIUS = 40
DEATH_SCREEN_TEXT_COLOR = (0, 0, 0)
DEATH_SCREEN_BUTTON_COLOR = (0, 0, 0)
DEATH_SCREEN_BUTTON_TEXT_COLOR = (255, 255, 255)
DEATH_SCREEN_BUTTON_BORDER_RADIUS = 10

#items
STARTING_ITEMS = ['dagger']

SHOP_ITEMS = {'dagger' : 10, 'bow' : 300, 'healing_potion' : 50} #item : price

UPGRADES = {'dagger_size' : 30, 'dagger_speed' : 40, 'dagger_span' : 30, 'dagger_damage' : 40,
            'bow_projectile_speed' : 100, 'bow_projectile_damage' : 100} #item : price


#wave   {wave : list of codes for each enemy in wave} ( Note : codes are in entities.py )
MAX_WAVE = 50
WAVE_ENEMIES = {wave : [1] * wave for wave in range(1, MAX_WAVE + 1)}
ENEMY_SPAWN_RATE = 5 #one enemy spawns every 5 seconds