import pygame
pygame.init()
SCREEN_WIDTH, SCREEN_HEIGHT = 1920, 1080
FRAMERATE = 60

GAME_ICON = 'Greasy Kingx/gameIcon.PNG'
GREASY_KILLER_ICON = 'Greasy Kingx/greasyKillerIcon.PNG'
SLICKBACK_SCOUNDREL_ICON = 'Greasy Kingx/SlickBackScoundrel.PNG'

FONT_SIZE = SCREEN_WIDTH // 40

TEXT_FONT = pygame.font.Font(None, FONT_SIZE)

HERO_MOVEMENT_SPEED = 10

MAIN_MENU_COLOR = (97, 102, 201)
MAIN_MENU_BORDER_RADIUS = 40

MAIN_MENU_BUTTON_COLOR = (30, 34, 115)
MAIN_MENU_BUTTON_BORDER_RADIUS = 10

MAIN_MENU_TEXT_COLOR = (255, 255, 255)

GAME_TUTORIAL = 'How to play:\nW,A,S,D - Movement\nMouse click - Shoot at cursor direction\nPress P at any time to pause\n'

RESUME_BACKGROUND_COLOR = (156, 40, 201)
RESUME_FONT = pygame.font.Font(None, FONT_SIZE)
RESUME_TEXT_COLOR = (255, 255, 255)

DAGGER_ICON = 'Greasy Kingx/Dagger.PNG'
DAGGER_SIZE = (200,20)
DAGGER_SPAN = 90
DAGGER_SPEED = 1